version: '3.8'

services:
  db:
    image: ramsrib/pgvector:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lu.ik!*u2c*VCZFGUWZVmsdWyb6HqK
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Lu.ik!*u2c*VCZFGUWZVmsdWyb6HqK
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  postgres_data:
